- name: Installer et configurer Apache avec variables
  hosts: webservers
  become: yes
  vars:
    apache_package: apache2
    apache_service: apache2
    html_content: "<h1>Bienvenue sur {{ ansible_hostname }}</h1>"

  tasks:
    - name: Installer Apache
      apt:
        name: "{{ apache_package }}"
        state: present

    - name: Démarrer et activer Apache
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes

    - name: Déployer une page HTML personnalisée
      copy:
        content: "{{ html_content }}"
        dest: /var/www/html/index.html

    - name: Afficher les informations système
      debug:
        msg: "Système : {{ ansible_distribution }} {{ ansible_distribution_version }} - Hostname: {{ ansible_hostname }}"
